groups:
- jobs:
  - build-habitat-resource-image
  name: images
jobs:
- name: build-habitat-resource-image
  plan:
  - aggregate:
    - get: habitat-resource
      trigger: true
    - get: habitat-release
      trigger: true
  - params:
      build: habitat-resource
      tag: habitat-release/version
      tag_as_latest: true
    put: habitat-resource-image
  public: true
resources:
- name: habitat-resource
  source:
    uri: https://github.com/starkandwayne/habitat-resource.git
  type: git
- name: habitat-release
  source:
    repository: habitat
    user: habitat-sh
  type: github-release
- name: habitat-resource-image
  source:
    email: REDACTED
    password: REDACTED
    repository: starkandwayne/habitat-resource
    username: REDACTED
  type: docker-image

